civ.register_material(c.."people", "People", "civ_person.png")
civ.register_material(c.."lumber", "Wood", "civ_lumber.png")
civ.register_material(c.."stone", "Stone", "civ_stone_item.png")
civ.register_material(c.."grain", "Grain", "civ_grain.png")
civ.register_material(c.."metal", "Metal", "civ_metal.png")
civ.register_material(c.."coal", "Coal", "civ_coal.png")
civ.register_material(c.."research", "Research", "civ_research.png")
civ.register_material(c.."crystal", "Crystal", "civ_crystal.png")
civ.register_material(c.."infused_crystal", "Infused Crystal", "civ_infused_crystal.png")
civ.register_material(c.."power", "Electricity", "civ_power.png")